# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: FairGuard Blog
description: > # this means to ignore newlines until "baseurl:"
  反外挂 u3d加密 手游保护 u3d 加固 mobile game protect unity3d 游戏保护 资源加密 assetbundle encrypt
baseurl: ""
url: "https://fairguard.github.io"
permalink: /:year/:month/:day/:title
repository: fairguard/fairguard.github.io
paginate: 15

# MatJek specific configurations
#github_profile: "https://github.com/ShawnTeoh"
#user: "f"
#user_email: "john@doe.com"
contact_url: "https://www.fair-guard.com"
#google_tracking_id: "UA-96359860-1"
#google_site_verification: "UA-96359860-1"
#disqus_shortname: "matjek"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
compress_html:
  blanklines:       true

excerpt_separator: '<!-- more -->'

auto_excerpt:
    enable: true

future: true
